"""Seed script for drills library and practice templates.

Call seed_drills(db) and seed_templates(db) from the /api/seed router.
Both functions are idempotent — they check whether data already exists
before inserting anything.
"""
from datetime import datetime

from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from models.drill import Drill, PracticeTemplate


# ---------------------------------------------------------------------------
# Drill seed data
# ---------------------------------------------------------------------------

DRILL_DATA = [
    # ── SOCCER ──────────────────────────────────────────────────────────────
    {
        "title": "Rondo 4v1",
        "sport": "soccer",
        "skill_focus": "passing",
        "difficulty": "intermediate",
        "duration_minutes": 15,
        "player_count_min": 5,
        "player_count_max": 6,
        "description": "Four players keep possession in a small circle while one defender tries to win the ball. Develops quick one-touch passing, spatial awareness, and decision-making under pressure.",
        "setup": "Mark a 10-yard circle with cones. Assign one player as the defender in the middle. The remaining four play on the outside.",
        "instructions": [
            "Four players stand on the perimeter of the circle, one defender inside.",
            "Outside players pass to each other trying to keep the ball away from the defender.",
            "Players should use one or two touches maximum.",
            "If the defender wins the ball, the player who lost it becomes the new defender.",
            "Rotate the defender every 90 seconds if no turnovers occur.",
        ],
        "coaching_points": [
            "Body shape open before receiving — scan before the ball arrives.",
            "Support angles: offer the passer two clear options at all times.",
            "Weight of pass matters — too soft and the defender can intercept.",
            "Communicate verbally to let teammates know when they're under pressure.",
        ],
        "progressions": [
            {"label": "Easier", "description": "Increase the circle size to 15 yards and allow unlimited touches."},
            {"label": "Harder", "description": "Add a second defender (4v2) or restrict to one-touch only."},
        ],
        "equipment": ["cones", "soccer ball"],
        "tags": ["possession", "passing", "pressure", "rondo"],
        "age_brackets": ["u10", "u12", "u14", "u16"],
        "is_featured": True,
    },
    {
        "title": "Wall Passing Combinations",
        "sport": "soccer",
        "skill_focus": "passing",
        "difficulty": "beginner",
        "duration_minutes": 10,
        "player_count_min": 2,
        "player_count_max": 4,
        "description": "Players practice give-and-go (wall pass) combinations in pairs, reinforcing timing, weight of pass, and movement after releasing the ball.",
        "setup": "Set two cones 15 yards apart. Players work in pairs, one on each cone.",
        "instructions": [
            "Player A passes to Player B and immediately sprints forward.",
            "Player B plays the ball into the space behind Player A in one touch.",
            "Player A receives the return pass on the move.",
            "After five repetitions, switch roles.",
            "Progress to adding a third cone for a three-player combination.",
        ],
        "coaching_points": [
            "Pass firmly to the front foot of your partner.",
            "Sprint immediately after releasing the ball — don't wait.",
            "Wall player should redirect with a firm, accurate one-touch pass.",
            "Communicate: call 'wall' before the pass.",
        ],
        "progressions": [
            {"label": "Easier", "description": "Shorten the distance between cones to 10 yards and allow two touches for the wall player."},
            {"label": "Harder", "description": "Add a passive defender at the midpoint to force the combination to be sharp and well-timed."},
        ],
        "equipment": ["cones", "soccer ball"],
        "tags": ["passing", "combination", "movement", "beginner"],
        "age_brackets": ["u8", "u10", "u12"],
        "is_featured": False,
    },
    {
        "title": "1v1 Defending",
        "sport": "soccer",
        "skill_focus": "defending",
        "difficulty": "intermediate",
        "duration_minutes": 12,
        "player_count_min": 4,
        "player_count_max": 12,
        "description": "Players practice individual defending principles — pressing, jockeying, and winning the ball — in 1v1 situations with a small goal to attack.",
        "setup": "Set up 10x15-yard channels with a small goal at each end. One attacker and one defender per channel.",
        "instructions": [
            "Attacker starts with the ball at one end of the channel.",
            "Defender closes down quickly but slows near the attacker.",
            "Defender tries to delay, channel the attacker toward the sideline, and win the ball.",
            "If the attacker scores or leaves the channel, reset and switch roles.",
            "Play 90-second rounds.",
        ],
        "coaching_points": [
            "Approach quickly but arrive under control — don't dive in.",
            "Stay on the balls of your feet; stay low and balanced.",
            "Show the attacker to their weak foot when possible.",
            "Wait for the attacker to take a heavy touch before committing.",
        ],
        "progressions": [
            {"label": "Easier", "description": "Widen the channel to 15 yards so the defender has more recovery time."},
            {"label": "Harder", "description": "Reduce the channel to 8 yards and add a shot-clock (attacker must shoot within 8 seconds)."},
        ],
        "equipment": ["cones", "small goals", "soccer ball"],
        "tags": ["defending", "1v1", "pressure", "individual"],
        "age_brackets": ["u10", "u12", "u14", "u16"],
        "is_featured": False,
    },
    {
        "title": "Shooting on Target",
        "sport": "soccer",
        "skill_focus": "shooting",
        "difficulty": "beginner",
        "duration_minutes": 15,
        "player_count_min": 4,
        "player_count_max": 12,
        "description": "Players take turns receiving a pass and shooting at goal, focusing on technique, accuracy, and follow-through.",
        "setup": "Two lines of players face the goal 18 yards out. A feeder (coach or player) stands at the top of the penalty area with a supply of balls.",
        "instructions": [
            "Player runs to receive a pass from the feeder.",
            "Player controls the ball and shoots at goal within two touches.",
            "Aim for corners — pick a target before receiving.",
            "Follow through: shoot through the ball, not at it.",
            "Rotate lines after each attempt.",
        ],
        "coaching_points": [
            "Plant foot beside the ball, not behind it.",
            "Strike with the laces for power or instep for placement.",
            "Keep the body over the ball to keep the shot low.",
            "Eyes on the ball at the moment of contact.",
        ],
        "progressions": [
            {"label": "Easier", "description": "Allow a static ball (no pass) so players can focus purely on technique."},
            {"label": "Harder", "description": "Add a passive goalkeeper or require a first-touch shot from a driven pass."},
        ],
        "equipment": ["cones", "goal", "multiple soccer balls"],
        "tags": ["shooting", "finishing", "technique", "beginner"],
        "age_brackets": ["u8", "u10", "u12", "u14"],
        "is_featured": True,
    },
    {
        "title": "Small-Sided 3v3",
        "sport": "soccer",
        "skill_focus": "game understanding",
        "difficulty": "intermediate",
        "duration_minutes": 20,
        "player_count_min": 6,
        "player_count_max": 8,
        "description": "Conditioned small-sided game that maximizes touches, decision-making, and transitions. Ideal for developing game intelligence in a simplified environment.",
        "setup": "25x35-yard field with small goals on each end. Two teams of three. Goalkeepers optional.",
        "instructions": [
            "Play continuous 3v3 with normal soccer rules.",
            "When a goal is scored, restart from the defending team's goalkeeper (or cone).",
            "Each player must touch the ball before their team can score.",
            "Coach pauses play to highlight decision moments (freeze coaching).",
            "Play 4-minute games, rotate teams.",
        ],
        "coaching_points": [
            "When we have the ball: third player creates width and depth.",
            "When we lose the ball: immediate counter-press — closest player wins it back.",
            "Look for the switch — change the point of attack when the defence is compact.",
            "Communication: name your teammate when you want the ball.",
        ],
        "progressions": [
            {"label": "Easier", "description": "Allow the team in possession to use a 'joker' player — an extra player who is always on the team with the ball."},
            {"label": "Harder", "description": "Add a two-touch restriction or require a set number of passes before shooting."},
        ],
        "equipment": ["cones", "small goals", "pinnies", "soccer ball"],
        "tags": ["small-sided", "game", "decision-making", "transitions"],
        "age_brackets": ["u10", "u12", "u14"],
        "is_featured": False,
    },
    {
        "title": "Goalkeeping Fundamentals",
        "sport": "soccer",
        "skill_focus": "goalkeeping",
        "difficulty": "beginner",
        "duration_minutes": 15,
        "player_count_min": 2,
        "player_count_max": 4,
        "description": "Introduces young goalkeepers to the correct ready position, basic handling, and footwork needed to make saves.",
        "setup": "Full-size or appropriately sized goal. Coach or feeder stands 8–12 yards from the keeper with multiple balls.",
        "instructions": [
            "Keeper sets into the ready stance: feet shoulder-width, slight knee bend, hands out front, weight on toes.",
            "Feeder throws or rolls balls to the keeper's right, left, and straight on.",
            "Keeper catches and returns the ball, resetting after each save.",
            "Work through three sets: (1) low balls, (2) mid-height, (3) above-shoulder.",
            "Switch keeper every 10 saves.",
        ],
        "coaching_points": [
            "Always be moving feet to get behind the ball — don't just reach.",
            "W-grip for balls above the waist; scoop grip for low balls.",
            "Soft hands — absorb the ball rather than stab at it.",
            "Call 'keeper!' loudly when coming for a crossed ball.",
        ],
        "progressions": [
            {"label": "Easier", "description": "Use a smaller, softer ball and shorten the distance to 6 yards."},
            {"label": "Harder", "description": "Progress to shots driven from 14 yards, forcing the keeper to set quickly."},
        ],
        "equipment": ["goal", "multiple soccer balls"],
        "tags": ["goalkeeping", "handling", "footwork", "beginner"],
        "age_brackets": ["u8", "u10", "u12"],
        "is_featured": False,
    },
    {
        "title": "Dribbling Slalom Course",
        "sport": "soccer",
        "skill_focus": "dribbling",
        "difficulty": "beginner",
        "duration_minutes": 10,
        "player_count_min": 2,
        "player_count_max": 16,
        "description": "Players dribble through a cone slalom course, practicing close ball control, change of direction, and both feet.",
        "setup": "Place 8 cones in a straight line, 2 yards apart. Create 2–4 parallel slalom lanes.",
        "instructions": [
            "Dribble through the cones using the outside of the right foot, then come back using the outside of the left foot.",
            "Keep the ball close — no more than one foot from your feet.",
            "Look up every 2–3 touches to build awareness.",
            "Race format: timed runs to add competitive element.",
            "Progress to using inside/outside cuts around each cone.",
        ],
        "coaching_points": [
            "Small, quick touches keep the ball close.",
            "Use both feet — don't favour your strong side.",
            "Accelerate out of the slalom at the end.",
            "Soft knees when changing direction.",
        ],
        "progressions": [
            {"label": "Easier", "description": "Increase cone spacing to 3 yards and allow unlimited touches."},
            {"label": "Harder", "description": "Reduce cone spacing to 1.5 yards and add a time limit — players who knock cones over must do 5 juggles before continuing."},
        ],
        "equipment": ["cones", "soccer ball"],
        "tags": ["dribbling", "ball control", "beginner", "individual"],
        "age_brackets": ["u6", "u8", "u10"],
        "is_featured": False,
    },
    {
        "title": "Crossing and Finishing",
        "sport": "soccer",
        "skill_focus": "crossing",
        "difficulty": "intermediate",
        "duration_minutes": 20,
        "player_count_min": 6,
        "player_count_max": 14,
        "description": "Players practice delivering crosses from wide positions while forwards attack the box and attempt to finish on goal.",
        "setup": "Full-size goal with goalkeeper. Two wide channels marked with cones at the 18-yard line. One line of crossers on each flank, one line of forwards in the box.",
        "instructions": [
            "Wide player dribbles to the end line or crossing zone and delivers a cross.",
            "Two forwards time their runs — near post and back post.",
            "Attackers must touch the ball before it passes the far post.",
            "Rotate: crosser goes to forward line, forward joins crosser line.",
            "Alternate sides after each cross.",
        ],
        "coaching_points": [
            "Crossers: get your head up before crossing — see where the runners are.",
            "Drive the ball to the near post for a flick-on, or float it to the back post for a header.",
            "Forwards: delay your run so you arrive as the ball arrives.",
            "Attack the ball — don't wait for it to come to you.",
        ],
        "progressions": [
            {"label": "Easier", "description": "Allow the crosser to stand still and cross from a stationary ball."},
            {"label": "Harder", "description": "Add a defender on each forward to make them win the header under pressure."},
        ],
        "equipment": ["cones", "goal", "goalkeeper gear", "multiple soccer balls", "pinnies"],
        "tags": ["crossing", "finishing", "wide play", "heading"],
        "age_brackets": ["u12", "u14", "u16"],
        "is_featured": False,
    },

    # ── BASKETBALL ──────────────────────────────────────────────────────────
    {
        "title": "Mikan Drill",
        "sport": "basketball",
        "skill_focus": "finishing",
        "difficulty": "beginner",
        "duration_minutes": 10,
        "player_count_min": 1,
        "player_count_max": 4,
        "description": "Classic finishing drill that develops soft touch around the basket using alternating lay-ups from each side of the rim.",
        "setup": "Player stands directly under the basket. No cones needed.",
        "instructions": [
            "Start on the right block with the ball.",
            "Jump off the left foot, extend the right hand, and lay the ball softly off the backboard.",
            "Without letting the ball touch the floor, catch the ball and immediately jump off the right foot for a left-handed lay-up.",
            "Continue alternating sides for 60 seconds.",
            "Count makes; target 20+ in 60 seconds.",
        ],
        "coaching_points": [
            "Use the backboard — aim for the top corner of the box.",
            "Keep the ball high throughout — don't drop it below the waist.",
            "Explode vertically; reach as high as possible at the peak.",
            "Soft touch: fingertip control, not a palm.",
        ],
        "progressions": [
            {"label": "Easier", "description": "Allow the ball to bounce once between each lay-up so the player has more time to reset."},
            {"label": "Harder", "description": "Add a power Mikan: catch, two-foot jump stop, then power up through contact."},
        ],
        "equipment": ["basketball", "hoop"],
        "tags": ["finishing", "lay-ups", "touch", "solo"],
        "age_brackets": ["u8", "u10", "u12", "u14"],
        "is_featured": True,
    },
    {
        "title": "3-Man Weave",
        "sport": "basketball",
        "skill_focus": "passing",
        "difficulty": "intermediate",
        "duration_minutes": 12,
        "player_count_min": 6,
        "player_count_max": 15,
        "description": "Classic three-player weave drill that builds passing accuracy, court vision, timing, and conditioning while moving the full length of the floor.",
        "setup": "Three lines at one baseline — left, center, right. Ball starts in the middle line.",
        "instructions": [
            "Center passes to the right and cuts behind them to the far side.",
            "Right player catches, passes to left, and cuts behind.",
            "Continue the weave pattern down the court.",
            "Finish with a lay-up from the player who last has the ball.",
            "Return with the same pattern going the other way.",
        ],
        "coaching_points": [
            "Pass ahead of the receiver — lead them into space.",
            "Sprint hard after every pass — the drill breaks down if players jog.",
            "No bad passes — be accurate even at speed.",
            "Finisher calls their name so teammates know who's taking the lay-up.",
        ],
        "progressions": [
            {"label": "Easier", "description": "Walk through the pattern first before adding full speed."},
            {"label": "Harder", "description": "Restrict to chest passes only, or add a defensive player who tries to deflect passes."},
        ],
        "equipment": ["basketball"],
        "tags": ["passing", "weave", "conditioning", "court vision"],
        "age_brackets": ["u10", "u12", "u14", "u16"],
        "is_featured": False,
    },
    {
        "title": "Partner Passing",
        "sport": "basketball",
        "skill_focus": "passing",
        "difficulty": "beginner",
        "duration_minutes": 8,
        "player_count_min": 2,
        "player_count_max": 20,
        "description": "Stationary partner passing drill covering chest pass, bounce pass, and overhead pass. Builds the foundational mechanics for all types of passes.",
        "setup": "Partners stand 10–12 feet apart facing each other. All pairs work simultaneously.",
        "instructions": [
            "Start with 20 chest passes: step into the pass, thumbs down at follow-through.",
            "Next 20 reps: bounce passes — aim to bounce the ball two-thirds of the way to your partner.",
            "Final 20 reps: overhead passes — release from above the forehead, snap the wrists.",
            "After each set, take one step back and repeat.",
            "Challenge: 30-second max reps contest.",
        ],
        "coaching_points": [
            "Step toward your partner with every pass.",
            "Thumbs rotate down and outward on release — 'break the thumbs.'",
            "Catch with two hands and pull the ball into your body.",
            "Keep elbows in on the overhead pass — don't wind up behind the head.",
        ],
        "progressions": [
            {"label": "Easier", "description": "Shorten the distance to 8 feet and allow partners to catch with one hand."},
            {"label": "Harder", "description": "Add movement — both players shuffle laterally while continuing to pass."},
        ],
        "equipment": ["basketball"],
        "tags": ["passing", "beginner", "fundamentals", "partner"],
        "age_brackets": ["u8", "u10", "u12"],
        "is_featured": False,
    },
    {
        "title": "Defensive Slides",
        "sport": "basketball",
        "skill_focus": "defending",
        "difficulty": "beginner",
        "duration_minutes": 8,
        "player_count_min": 2,
        "player_count_max": 20,
        "description": "Players develop proper defensive footwork through lateral slide, retreat step, and closeout mechanics without a ball.",
        "setup": "Players spread across the lane lines or use cones to mark a 12-foot lateral course.",
        "instructions": [
            "Start in athletic stance: feet wide, hips low, back straight, hands active.",
            "Slide laterally to the right cone — push with the left foot, don't cross feet.",
            "Touch the cone, reverse direction, slide to the left cone.",
            "Complete 10 trips (5 each direction), rest 20 seconds, repeat.",
            "Progress to closeout drill: start under basket, sprint to cone, chop feet.",
        ],
        "coaching_points": [
            "Stay low throughout — don't pop up between slides.",
            "Keep feet at least shoulder-width apart; never let them touch.",
            "Active hands: one high, one low to deter passes.",
            "Eyes on the ball handler's hips — don't watch the ball.",
        ],
        "progressions": [
            {"label": "Easier", "description": "Reduce the slide distance to 8 feet and focus on form over speed."},
            {"label": "Harder", "description": "Add a partner pointing left/right randomly — defender must react and slide on each command."},
        ],
        "equipment": ["cones"],
        "tags": ["defending", "footwork", "slides", "beginner"],
        "age_brackets": ["u8", "u10", "u12", "u14"],
        "is_featured": False,
    },
    {
        "title": "Ball Handling Figure 8",
        "sport": "basketball",
        "skill_focus": "dribbling",
        "difficulty": "beginner",
        "duration_minutes": 8,
        "player_count_min": 1,
        "player_count_max": 20,
        "description": "Players dribble the ball in a figure-eight pattern through and around their legs, building hand strength, coordination, and low dribble control.",
        "setup": "Players spread out with their own ball, feet slightly wider than shoulder-width.",
        "instructions": [
            "Start with the ball in the right hand.",
            "Dribble between legs to the left hand, then around the outside of the left leg.",
            "Continue the figure-eight pattern — front to back, back to front.",
            "Complete 30 seconds forward, then 30 seconds reverse (ball travels opposite direction).",
            "Focus on keeping the dribble below knee height.",
        ],
        "coaching_points": [
            "Stay low — bend at the knees, not the waist.",
            "Dribble with your fingertips, not your palm.",
            "Push the ball through quickly and smoothly.",
            "Keep your eyes up once you have the pattern memorised.",
        ],
        "progressions": [
            {"label": "Easier", "description": "Pass the ball around the legs without dribbling first to learn the footwork."},
            {"label": "Harder", "description": "Add a crossover between each figure-eight rep, or perform the drill while walking forward."},
        ],
        "equipment": ["basketball"],
        "tags": ["dribbling", "ball handling", "coordination", "solo"],
        "age_brackets": ["u8", "u10", "u12"],
        "is_featured": False,
    },
    {
        "title": "Pick and Roll Fundamentals",
        "sport": "basketball",
        "skill_focus": "offense",
        "difficulty": "intermediate",
        "duration_minutes": 15,
        "player_count_min": 4,
        "player_count_max": 10,
        "description": "Teaches the two-player pick-and-roll action, covering proper screen setting, reading the defense, and the roll or pop decision for the screener.",
        "setup": "Half-court. Ball handler starts at top of key, screener starts at elbow.",
        "instructions": [
            "Screener sets a flat, legal screen on the ball handler's defender.",
            "Ball handler uses the screen by dribbling off the screener's shoulder.",
            "Screener rolls hard to the basket or pops to the elbow based on the defense.",
            "Ball handler reads the defense: drive if the screen is switched, pass to the roller if help collapses.",
            "Rotate roles after 5 reps; add a passive defender after basics are solid.",
        ],
        "coaching_points": [
            "Screener: set a wide, stationary screen — feet wide, arms crossed, brace for contact.",
            "Ball handler: hesitate before the screen to let it be set, then attack hard off the shoulder.",
            "Roll player: seal the defender, show target hand, finish strong.",
            "Read the defense together — the correct decision depends on what the defense gives you.",
        ],
        "progressions": [
            {"label": "Easier", "description": "Remove the defender and walk through the coverage options (switch, hedge, drop) verbally."},
            {"label": "Harder", "description": "Add two live defenders and a help defender to create real coverage decisions."},
        ],
        "equipment": ["basketball", "cones"],
        "tags": ["pick and roll", "offense", "two-player", "reading defense"],
        "age_brackets": ["u12", "u14", "u16"],
        "is_featured": True,
    },

    # ── BASEBALL ────────────────────────────────────────────────────────────
    {
        "title": "Tee Work Fundamentals",
        "sport": "baseball",
        "skill_focus": "hitting",
        "difficulty": "beginner",
        "duration_minutes": 15,
        "player_count_min": 1,
        "player_count_max": 8,
        "description": "Players work through structured tee rounds to build a consistent, repeatable swing with proper stance, load, and follow-through.",
        "setup": "Batting tee at plate or hitting tunnel. Set tee height to top of the strike zone, then move to middle and low positions.",
        "instructions": [
            "Start with feet shoulder-width apart, slight knee bend, hands at shoulder height.",
            "Load: shift weight to back leg slightly, hands move back.",
            "Drive: lower half initiates — hips rotate before hands.",
            "Contact: knob leads, barrel follows — hit through the ball to center field.",
            "Complete 10 swings at each tee height (high, middle, low) before moving on.",
        ],
        "coaching_points": [
            "Squish the bug — pivot back foot through contact.",
            "Keep the barrel above the hands until the contact zone.",
            "Extension: both arms extend fully after contact.",
            "Finish: hands follow through to shoulder level on the opposite side.",
        ],
        "progressions": [
            {"label": "Easier", "description": "Remove the tee and have players rehearse the swing mechanics with no ball (dry swings) in slow motion."},
            {"label": "Harder", "description": "Move the tee inside and outside the plate to simulate different pitch locations."},
        ],
        "equipment": ["batting tee", "baseball bat", "baseballs", "helmet", "batting cage (optional)"],
        "tags": ["hitting", "tee work", "mechanics", "beginner"],
        "age_brackets": ["u8", "u10", "u12"],
        "is_featured": True,
    },
    {
        "title": "Soft Toss",
        "sport": "baseball",
        "skill_focus": "hitting",
        "difficulty": "beginner",
        "duration_minutes": 12,
        "player_count_min": 2,
        "player_count_max": 8,
        "description": "A feeder tosses balls underhand from the side while the batter focuses on timing, balance, and hitting to all fields.",
        "setup": "Feeder kneels or sits 5–7 feet to the side and slightly in front of the batter. Batter faces a net or fence.",
        "instructions": [
            "Feeder tosses a soft, arcing toss into the contact zone.",
            "Batter loads and drives through the ball as it enters the zone.",
            "Aim for 10 swings to center field, 10 to the opposite field, 10 pulled.",
            "Feeder should call out the target field before each toss.",
            "Change feeders every 30 swings.",
        ],
        "coaching_points": [
            "Stay back — don't lunge at the ball; let it travel into the zone.",
            "Inside pitch: get the hands in early, pull the barrel through.",
            "Outside pitch: stay back and drive it to the opposite field.",
            "Head down through contact — watch the ball onto the bat.",
        ],
        "progressions": [
            {"label": "Easier", "description": "Use a larger, softer ball (tennis ball or oversized training ball) so the batter can see it more easily."},
            {"label": "Harder", "description": "Add a called location — feeder calls 'in,' 'out,' or 'middle' as the ball is released."},
        ],
        "equipment": ["baseballs", "baseball bat", "helmet", "L-screen or net"],
        "tags": ["hitting", "soft toss", "timing", "beginner"],
        "age_brackets": ["u8", "u10", "u12", "u14"],
        "is_featured": False,
    },
    {
        "title": "Four Corners Throwing",
        "sport": "baseball",
        "skill_focus": "throwing",
        "difficulty": "beginner",
        "duration_minutes": 10,
        "player_count_min": 4,
        "player_count_max": 16,
        "description": "Players stand at four base positions and throw around the horn in sequence to build arm strength, accuracy, and footwork on each throw.",
        "setup": "Players at each base (home, first, second, third). Extra players wait behind each base.",
        "instructions": [
            "Start at home plate. Player throws to third base.",
            "Third throws to second, second throws to first, first throws home.",
            "Reverse direction after 5 rounds.",
            "Work on hitting the cutoff: chest-high throws that can be handled cleanly.",
            "Time the round: fastest accurate completion wins.",
        ],
        "coaching_points": [
            "Four-seam grip before every throw — fingers across the seams.",
            "Stride toward your target — point your glove-side shoulder at the receiver.",
            "Short arm action: compact and quick, especially on the infield.",
            "Receiver gives a target with the glove before the throw leaves the hand.",
        ],
        "progressions": [
            {"label": "Easier", "description": "Shorten the distance between bases and allow players to take an extra step before throwing."},
            {"label": "Harder", "description": "Add a ground ball start — fielder picks up a rolled ball and then begins the four-corner sequence."},
        ],
        "equipment": ["baseballs", "baseball gloves", "bases"],
        "tags": ["throwing", "accuracy", "infield", "beginner"],
        "age_brackets": ["u8", "u10", "u12"],
        "is_featured": False,
    },
    {
        "title": "Ground Ball Fielding",
        "sport": "baseball",
        "skill_focus": "fielding",
        "difficulty": "intermediate",
        "duration_minutes": 15,
        "player_count_min": 2,
        "player_count_max": 12,
        "description": "Infielders practice receiving ground balls with proper footwork, glove position, and transfer to a throw.",
        "setup": "Coach or feeder stands at home plate with a bucket of balls. Infielders in their positions.",
        "instructions": [
            "Coach rolls or hits a ground ball to each infielder in turn.",
            "Infielder charges the ball (when appropriate), gets low, and fields with glove palm up.",
            "Transfer quickly: bare hand covers the ball in the glove, grip, and throw.",
            "Throw to a target at first base.",
            "Alternate soft rollers, hard choppers, and balls to the backhand side.",
        ],
        "coaching_points": [
            "Get your glove down early — it's easier to come up than to go down.",
            "Funnel the ball to the belly button on routine grounders.",
            "Momentum toward the target: don't field and then pivot — move through the ball.",
            "Bare hand stays close — no 'alligator arm.'",
        ],
        "progressions": [
            {"label": "Easier", "description": "Use a soft training ball or rolled tennis ball to reduce fear of bad hops."},
            {"label": "Harder", "description": "Hit live ground balls at speed, including difficult backhands and balls in the hole."},
        ],
        "equipment": ["baseballs", "baseball gloves", "bases", "bat", "bucket"],
        "tags": ["fielding", "grounders", "infield", "intermediate"],
        "age_brackets": ["u10", "u12", "u14"],
        "is_featured": False,
    },
    {
        "title": "Fly Ball Drops",
        "sport": "baseball",
        "skill_focus": "fielding",
        "difficulty": "intermediate",
        "duration_minutes": 12,
        "player_count_min": 2,
        "player_count_max": 10,
        "description": "Outfielders practice reading fly ball angles, taking the correct drop step, and making a clean catch with proper footwork.",
        "setup": "Coach or feeder stands at home plate. Outfielders in left-center and right-center.",
        "instructions": [
            "Coach tosses or hits a fly ball over the outfielder's left or right shoulder.",
            "Outfielder reads the ball, takes a drop step in the correct direction, and runs to the spot.",
            "Catch the ball in front of the throwing shoulder when possible.",
            "Immediately set feet and throw to a relay cutoff.",
            "Alternate short fly balls and deep fly balls.",
        ],
        "coaching_points": [
            "First step is the drop step — don't backpedal, turn and run.",
            "Keep both eyes on the ball throughout the flight.",
            "Squeeze the catch — don't reach; let it come to you.",
            "On deep balls, beat the ball to the spot and let it come down to you.",
        ],
        "progressions": [
            {"label": "Easier", "description": "Throw soft, high-arc fly balls so the outfielder has more time to read and react."},
            {"label": "Harder", "description": "Hit deep line drives that require a full sprint and over-the-shoulder catch."},
        ],
        "equipment": ["baseballs", "baseball gloves", "bat", "bucket"],
        "tags": ["fielding", "fly balls", "outfield", "intermediate"],
        "age_brackets": ["u10", "u12", "u14", "u16"],
        "is_featured": False,
    },
    {
        "title": "Pitching Mechanics",
        "sport": "baseball",
        "skill_focus": "pitching",
        "difficulty": "intermediate",
        "duration_minutes": 20,
        "player_count_min": 2,
        "player_count_max": 6,
        "description": "Pitchers work through a segmented mechanics routine — balance point, stride, arm path, and finish — focusing on repeatable delivery and command.",
        "setup": "Pitcher on a mound or flat ground. Catcher or net 46–60 feet away (age appropriate).",
        "instructions": [
            "Segment 1 — Balance drill: lift knee to hip height, hold for 2 seconds, feel the balance point.",
            "Segment 2 — Stride drill: from balance, stride directly toward the target — no drift.",
            "Segment 3 — Arm path: guided throws at 50% effort, elbow at shoulder height, external rotation before release.",
            "Segment 4 — Full delivery at 75% effort focusing on repeating the mechanics.",
            "Throw 3 sets of 10 pitches at each phase.",
        ],
        "coaching_points": [
            "Chin over the belly button at balance point.",
            "Stride foot closes slightly — don't open the hips too early.",
            "Elbow leads, then the forearm whips through at release.",
            "Finish: throwing arm follows through across the opposite knee.",
        ],
        "progressions": [
            {"label": "Easier", "description": "Work from the windup position only; no set position until the delivery is consistent."},
            {"label": "Harder", "description": "Add a target zone (taped on net or held by catcher) and track command percentage."},
        ],
        "equipment": ["baseballs", "pitching mound or rubber", "catcher's gear", "net"],
        "tags": ["pitching", "mechanics", "command", "intermediate"],
        "age_brackets": ["u10", "u12", "u14", "u16"],
        "is_featured": True,
    },

    # ── FOOTBALL ────────────────────────────────────────────────────────────
    {
        "title": "Route Running Basics",
        "sport": "football",
        "skill_focus": "receiving",
        "difficulty": "beginner",
        "duration_minutes": 15,
        "player_count_min": 2,
        "player_count_max": 12,
        "description": "Wide receivers practice the three foundational routes — slant, curl, and out — focusing on precise cuts, stem, and hand positioning at the catch point.",
        "setup": "Line of receivers at the line of scrimmage. QB or coach stands 5 yards behind to throw. Cones mark cut points.",
        "instructions": [
            "Rep 1 — Slant: release off the ball, take 3 steps up field, plant outside foot, cut at 45 degrees inside, look for the ball immediately.",
            "Rep 2 — Curl: 8 steps up field, plant, curl back toward the QB at 180 degrees, come back to the ball.",
            "Rep 3 — Out: 6 steps up field, plant inside foot, break hard at 90 degrees toward the sideline.",
            "Each receiver runs 3 reps of each route before rotating.",
            "Emphasize the break first, then add the catch.",
        ],
        "coaching_points": [
            "Sell the vertical before the cut — make the defender respect the go route.",
            "Sharp cuts: low hips, plant the outside foot, explode out.",
            "Catch with your hands, not your body — soft hands, eyes through the ball.",
            "Tuck and run immediately after the catch.",
        ],
        "progressions": [
            {"label": "Easier", "description": "Walk through each route without a ball first, then add a throw at half speed."},
            {"label": "Harder", "description": "Add a defender who mirrors the receiver at 1 yard off, forcing sharper cuts."},
        ],
        "equipment": ["cones", "football"],
        "tags": ["receiving", "routes", "WR", "beginner"],
        "age_brackets": ["u10", "u12", "u14"],
        "is_featured": False,
    },
    {
        "title": "Snap and Hand-Off Exchange",
        "sport": "football",
        "skill_focus": "fundamentals",
        "difficulty": "beginner",
        "duration_minutes": 10,
        "player_count_min": 3,
        "player_count_max": 10,
        "description": "Centers, quarterbacks, and running backs practice the snap exchange and hand-off, building the rhythmic timing needed for every running play.",
        "setup": "Center and QB in formation. Running back 4 yards behind in hand-off depth. No defense.",
        "instructions": [
            "Center snaps the ball cleanly to the QB's hands (under center).",
            "QB secures the ball, opens the hips, and rides the ball into the RB's pocket.",
            "RB opens the pocket — inside arm up, outside arm down — and covers the ball once received.",
            "Work through 10 reps to the right and 10 to the left.",
            "Progress to QB faking to one side, then handing off the other way.",
        ],
        "coaching_points": [
            "Center: solid base, snap directly up into the QB's hands.",
            "QB: hands form a firm target under center; don't slap or grab.",
            "Hand-off: ride the back — don't shove; let them take it.",
            "RB: secure the ball with both arms before anything else.",
        ],
        "progressions": [
            {"label": "Easier", "description": "Practice the hand-off without the snap first — QB starts with the ball."},
            {"label": "Harder", "description": "Add a linebacker at the second level who reacts after the snap, forcing the RB to read and hit the right hole."},
        ],
        "equipment": ["football"],
        "tags": ["fundamentals", "hand-off", "OL", "QB", "RB"],
        "age_brackets": ["u8", "u10", "u12"],
        "is_featured": False,
    },
    {
        "title": "Tackling Form",
        "sport": "football",
        "skill_focus": "defense",
        "difficulty": "beginner",
        "duration_minutes": 15,
        "player_count_min": 4,
        "player_count_max": 20,
        "description": "Defenders practice safe, fundamentally sound tackling technique — breakdown, buzz, wrap, and drive — using bag and form-tackle progressions.",
        "setup": "Tackle bags or blocking shields. Defenders pair up — one holds the bag, one tackles.",
        "instructions": [
            "Breakdown: approach the ball carrier, feet wide, hips low, eyes up.",
            "Buzz: short choppy steps to control momentum as contact is made.",
            "Contact point: forehead on numbers — not the top of the helmet.",
            "Wrap: both arms wrap tightly around the waist or thighs.",
            "Drive: legs churn through contact until forward progress stops.",
        ],
        "coaching_points": [
            "Eyes up — see what you hit; don't lead with the crown of the helmet.",
            "Hit through the ball carrier, not at them — keep legs pumping.",
            "The tackle starts with the breakdown — poor angles lead to missed tackles.",
            "Bring the hips through on contact — power comes from the legs, not the arms.",
        ],
        "progressions": [
            {"label": "Easier", "description": "Practice only the wrap and drive phase with a stationary bag before adding approach footwork."},
            {"label": "Harder", "description": "Add a ball carrier with a half-speed cut, forcing the defender to adjust the angle."},
        ],
        "equipment": ["tackle bags or blocking shields", "football helmets", "pads"],
        "tags": ["tackling", "defense", "fundamentals", "safety"],
        "age_brackets": ["u10", "u12", "u14"],
        "is_featured": False,
    },
    {
        "title": "7-on-7 Skeleton",
        "sport": "football",
        "skill_focus": "team",
        "difficulty": "advanced",
        "duration_minutes": 30,
        "player_count_min": 14,
        "player_count_max": 22,
        "description": "Passing-focused scrimmage between 7 offensive skill players and 7 defensive backs/linebackers. No linemen — focuses on route concepts, coverages, and QB reads.",
        "setup": "Full width of the field, offensive line of scrimmage at 20-yard line. QB, 3 WR, 2 TE/slots, 1 RB vs. 4 DBs, 3 LBs.",
        "instructions": [
            "Offense runs scripted or live pass plays from the playbook.",
            "Defense calls coverage and executes pre-snap and post-snap adjustments.",
            "QB must make a pre-snap read and identify the coverage.",
            "Drive is dead after every catch or incompletion — move to next play.",
            "Score: offense gets 1 point per completion, defense gets 1 point per PBU or INT.",
        ],
        "coaching_points": [
            "QB: go through progressions — primary, secondary, check-down, scramble.",
            "DBs: communicate coverage calls — no silent secondary.",
            "WRs: run routes to the boundary of the assigned concept, don't freelance.",
            "LBs: zone drops must honour the QB's eyes — don't just run to a spot.",
        ],
        "progressions": [
            {"label": "Easier", "description": "Run scripted plays only — defense knows the concept being run but not the exact route."},
            {"label": "Harder", "description": "Add a full-speed pass rush from a coach or designated rusher to put pressure on the QB."},
        ],
        "equipment": ["footballs", "cones", "pinnies"],
        "tags": ["7-on-7", "passing", "team", "advanced", "scrimmage"],
        "age_brackets": ["u14", "u16", "u18"],
        "is_featured": True,
    },
    {
        "title": "QB Footwork and Drop Backs",
        "sport": "football",
        "skill_focus": "quarterback",
        "difficulty": "intermediate",
        "duration_minutes": 12,
        "player_count_min": 1,
        "player_count_max": 4,
        "description": "Quarterbacks practice the three-step, five-step, and seven-step drop-back sequences with correct footwork, balance, and platform mechanics.",
        "setup": "QB at a centre with or without a snap. Cones mark the depth of each drop.",
        "instructions": [
            "3-step drop: quick catch from under centre, three quick steps, set, throw.",
            "5-step drop: five steps finishing on the back foot, hitch if needed, throw.",
            "7-step drop: power steps back, final two steps balance and gather, throw on rhythm.",
            "Add a shuffle step when the primary is not open before throwing the secondary.",
            "Complete 5 reps of each drop type per session.",
        ],
        "coaching_points": [
            "First step is a big directional step — establish the drop line quickly.",
            "Land on the back foot to gather power before throwing.",
            "Keep the ball at chest height throughout the drop — no dipping.",
            "Eyes downfield throughout the drop — never look at your feet.",
        ],
        "progressions": [
            {"label": "Easier", "description": "Practice the footwork pattern with no throw, focusing entirely on the mechanics of the drop."},
            {"label": "Harder", "description": "Add a live target at each throw point and require the QB to hit a specific landmark (hash, numbers, sideline)."},
        ],
        "equipment": ["footballs", "cones"],
        "tags": ["quarterback", "footwork", "drop back", "mechanics"],
        "age_brackets": ["u12", "u14", "u16"],
        "is_featured": False,
    },

    # ── VOLLEYBALL ──────────────────────────────────────────────────────────
    {
        "title": "Pepper Drill",
        "sport": "volleyball",
        "skill_focus": "passing",
        "difficulty": "beginner",
        "duration_minutes": 10,
        "player_count_min": 2,
        "player_count_max": 20,
        "description": "Two-player drill where partners continuously pass, set, and hit to each other without letting the ball touch the ground, building all three primary contacts in a continuous sequence.",
        "setup": "Pairs of players spread across the gym, 8–10 feet apart. One ball per pair.",
        "instructions": [
            "Player A serves a free ball underhand to Player B.",
            "Player B passes (bump) back to Player A.",
            "Player A sets the ball up high to Player B.",
            "Player B attacks (controlled hit or downward swing).",
            "Player A passes, Player B sets, Player A attacks, and so on.",
            "Target: 20 consecutive exchanges without the ball touching the floor.",
        ],
        "coaching_points": [
            "Pass: platform flat, arms away from body, angle platform toward the target.",
            "Set: hands contact the ball simultaneously above the forehead, push with fingertips.",
            "Attack: approach, jump, swing high to low — a controlled swing, not full power.",
            "Communicate on every ball.",
        ],
        "progressions": [
            {"label": "Easier", "description": "Remove the attack — pass and set only, allowing a bounce between contacts."},
            {"label": "Harder", "description": "Move farther apart and require the attack to be a full arm-swing spike (partners dig the attack)."},
        ],
        "equipment": ["volleyball"],
        "tags": ["passing", "setting", "pepper", "partner", "beginner"],
        "age_brackets": ["u10", "u12", "u14"],
        "is_featured": True,
    },
    {
        "title": "Serve Receive Lines",
        "sport": "volleyball",
        "skill_focus": "serving",
        "difficulty": "beginner",
        "duration_minutes": 12,
        "player_count_min": 4,
        "player_count_max": 16,
        "description": "Servers practice float and topspin serves from the end line while receivers work on positioning, platform angle, and directing passes to the setter target zone.",
        "setup": "Two servers behind the service line. Three receivers in a passing formation on the other side. Setter target at position 3.",
        "instructions": [
            "Server serves to any zone on the court.",
            "Receivers call the ball, pass to the setter target (position 3).",
            "Award 1 point for a pass that lands in the setter zone, 0 for out-of-system.",
            "Rotate servers and receivers every 10 serves.",
            "Servers work on placement — aim for deep corners and seams between receivers.",
        ],
        "coaching_points": [
            "Servers: contact the ball at its highest point; don't toss it forward.",
            "Receivers: move feet first, then platform — no reaching.",
            "Call the ball loudly: 'mine!' before touching it.",
            "Platform angle: if the ball is coming low, lean the platform back slightly.",
        ],
        "progressions": [
            {"label": "Easier", "description": "Allow underhand serves only so the server can control placement and pace."},
            {"label": "Harder", "description": "Add a serving target challenge — server must hit one of four designated cones to score a bonus point."},
        ],
        "equipment": ["volleyball", "cones"],
        "tags": ["serving", "serve receive", "passing", "beginner"],
        "age_brackets": ["u10", "u12", "u14"],
        "is_featured": False,
    },
    {
        "title": "3-Hit Combination",
        "sport": "volleyball",
        "skill_focus": "offense",
        "difficulty": "intermediate",
        "duration_minutes": 15,
        "player_count_min": 6,
        "player_count_max": 12,
        "description": "Full offense team reps executing a complete three-contact sequence — pass, set, attack — against no block, focusing on system execution and setter decisions.",
        "setup": "Full net. One side has 6 offensive players in system. Coach on the other side feeds free balls.",
        "instructions": [
            "Coach feeds a free ball from position 5 to the passing zone.",
            "Libero or passer digs the free ball to the setter.",
            "Setter runs to position 3 and sets to an outside, opposite, or middle hitter.",
            "Attacker approaches and executes a full swing.",
            "Award points for completed three-contact sequences and kills.",
        ],
        "coaching_points": [
            "Setter: call your target — communicate before the ball arrives.",
            "Attacker: read the setter's shoulders to anticipate where the set is going.",
            "Passers: platform stable and consistent so the setter gets a reliable ball.",
            "Every kill starts with a good pass.",
        ],
        "progressions": [
            {"label": "Easier", "description": "Coach hand-delivers a tossed ball directly to the setter so only the set-attack sequence is practiced."},
            {"label": "Harder", "description": "Add a two-person block on the attacking side to force the attacker to adjust angles and tips."},
        ],
        "equipment": ["volleyball", "volleyball net"],
        "tags": ["offense", "three-hit", "team", "intermediate"],
        "age_brackets": ["u12", "u14", "u16"],
        "is_featured": False,
    },
    {
        "title": "Block Footwork",
        "sport": "volleyball",
        "skill_focus": "defense",
        "difficulty": "intermediate",
        "duration_minutes": 12,
        "player_count_min": 2,
        "player_count_max": 8,
        "description": "Middle and outside blockers practice lateral footwork patterns — slide step, crossover, and swing — to reach any blocking position from the middle.",
        "setup": "Blockers at the net at position 3. Cones mark positions 2, 3, and 4.",
        "instructions": [
            "Slide step drill: from position 3, slide to position 4 and back — stay square to the net.",
            "Crossover drill: from position 3, crossover step to position 2 — turn hips, crossover with lead foot, finish parallel to net.",
            "Swing step drill: full swing from position 3 to position 4 in 2 steps for middles.",
            "Jump and penetrate: practice penetrating hands over the net at each position.",
            "Coach calls the position — blockers react and move.",
        ],
        "coaching_points": [
            "Stay low between jumps — don't stand up between moves.",
            "Keep hips parallel to the net throughout all footwork patterns.",
            "Hands-on contact must be over the plane of the net — reach, don't just jump.",
            "Read the setter's body early — don't wait for the ball to leave the hands.",
        ],
        "progressions": [
            {"label": "Easier", "description": "Practice footwork only without jumping — focus on efficient foot patterns."},
            {"label": "Harder", "description": "Add a setter and attacker — blocker must read the setter and commit to the correct blocking position."},
        ],
        "equipment": ["volleyball net", "cones"],
        "tags": ["blocking", "defense", "footwork", "intermediate"],
        "age_brackets": ["u12", "u14", "u16"],
        "is_featured": False,
    },
    {
        "title": "Setting Accuracy Targets",
        "sport": "volleyball",
        "skill_focus": "setting",
        "difficulty": "beginner",
        "duration_minutes": 12,
        "player_count_min": 2,
        "player_count_max": 8,
        "description": "Setters work on delivering consistently accurate sets to designated target zones using proper hand contact and follow-through.",
        "setup": "Setter at position 3. Targets (cones or hoops) placed at the outside hitting zone (position 4) and right side (position 2). Passer feeds the setter.",
        "instructions": [
            "Passer delivers the ball to the setter at position 3.",
            "Coach calls 'outside' or 'right' before the ball reaches the setter.",
            "Setter sets to the called position, landing the ball in the target zone.",
            "Award 1 point for sets that land within the target, 0 for off-target.",
            "Work in sets of 20 reps, track accuracy percentage.",
        ],
        "coaching_points": [
            "Face your right shoulder toward the target before the ball arrives.",
            "Hand shape: thumbs in, fingers spread — form a triangle with the thumbs and index fingers.",
            "Contact above the forehead — not behind the head.",
            "Push through the set — extend elbows and wrists completely.",
        ],
        "progressions": [
            {"label": "Easier", "description": "Toss the ball to yourself and set from a stationary position."},
            {"label": "Harder", "description": "Add a back-set option — coach calls 'back' and the setter must set backward to position 2 without turning."},
        ],
        "equipment": ["volleyball", "cones or hoops"],
        "tags": ["setting", "accuracy", "beginner", "individual"],
        "age_brackets": ["u10", "u12", "u14"],
        "is_featured": False,
    },
    {
        "title": "Jump Serve Development",
        "sport": "volleyball",
        "skill_focus": "serving",
        "difficulty": "advanced",
        "duration_minutes": 15,
        "player_count_min": 2,
        "player_count_max": 6,
        "description": "Advanced servers develop the jump topspin serve through a progressive approach: toss consistency, approach timing, and full jump serve mechanics.",
        "setup": "Server behind the service line. Partner or ball cart behind them. Open court to serve into.",
        "instructions": [
            "Phase 1 — Toss only: toss the ball high (3–4 feet above reach) and slightly in front of the right shoulder. Catch without serving. Repeat 10x.",
            "Phase 2 — Approach and jump: add the 4-step approach (right-left-right-left for right-handers) and jump without serving.",
            "Phase 3 — Full serve at 70%: combine toss, approach, and swing. Focus on hitting the top half of the ball.",
            "Phase 4 — Full power serves: 5 serves targeting specific court zones.",
        ],
        "coaching_points": [
            "Toss is the most important step — a bad toss means a bad serve.",
            "Snap the wrist aggressively over the top of the ball to create topspin.",
            "Contact point is high and slightly in front of the hitting shoulder.",
            "Land inside the court — step over the service line on the jump.",
        ],
        "progressions": [
            {"label": "Easier", "description": "Stay with a float jump serve — same approach but a stiff-wrist, open-hand contact for no spin."},
            {"label": "Harder", "description": "Target specific 3-foot zones (cones in corners) and track in/out percentage per zone."},
        ],
        "equipment": ["volleyball", "cones"],
        "tags": ["serving", "jump serve", "advanced", "individual"],
        "age_brackets": ["u14", "u16", "u18"],
        "is_featured": True,
    },
]


# ---------------------------------------------------------------------------
# Practice template seed data
# ---------------------------------------------------------------------------

TEMPLATE_DATA = [
    # ── SOCCER ──────────────────────────────────────────────────────────────
    {
        "title": "Soccer Beginner — Passing and Movement",
        "sport": "soccer",
        "age_bracket": "u10",
        "difficulty": "beginner",
        "duration_minutes": 60,
        "player_count_min": 8,
        "player_count_max": 14,
        "description": "A 60-minute beginner soccer session focused on foundational passing and movement. Suitable for U10 players with limited experience.",
        "overview": "Players learn to pass with the inside of the foot, support their teammates, and combine using simple give-and-go patterns. The session ends with a fun small-sided game.",
        "phases": [
            {
                "name": "Warm-Up",
                "duration_minutes": 10,
                "color": "amber",
                "activities": [
                    "Dribble free in a 20x20 grid — coach calls colours of cones to touch",
                    "Stretches: hip circles, high knees, butt kicks",
                    "Gates game: dribble through as many 2-cone gates as possible in 90 seconds",
                ],
            },
            {
                "name": "Technical — Passing Technique",
                "duration_minutes": 15,
                "color": "blue",
                "activities": [
                    "Partner passing in pairs (10 yards): inside foot, 20 reps each",
                    "Introduce 'plant foot beside the ball, kick through the middle'",
                    "Progress to moving passes: pass and follow your pass to partner's position",
                ],
            },
            {
                "name": "Skill Activity — Wall Pass Combinations",
                "duration_minutes": 15,
                "color": "green",
                "activities": [
                    "Wall Passing Combinations drill (see Drills Library)",
                    "Groups of 3: A passes to B, B plays one-touch back, A passes to C",
                    "Freeze coaching: highlight supporting angles",
                ],
            },
            {
                "name": "Game — 4v4 Small-Sided",
                "duration_minutes": 15,
                "color": "purple",
                "activities": [
                    "4v4 on a 30x20 yard field, small goals each end",
                    "Award bonus point for a completed wall pass during a game",
                    "Debrief: what did good passing look like today?",
                ],
            },
            {
                "name": "Cool-Down",
                "duration_minutes": 5,
                "color": "gray",
                "activities": [
                    "Guided light jog around the field",
                    "Quad, hamstring, and calf stretches",
                    "Team talk: one thing each player learned today",
                ],
            },
        ],
        "equipment_list": ["cones (assorted colours)", "soccer balls (1 per 2 players)", "small goals or cone goals"],
        "tags": ["beginner", "passing", "u10", "small-sided"],
        "is_featured": True,
    },
    {
        "title": "Soccer Intermediate — Possession and Pressure",
        "sport": "soccer",
        "age_bracket": "u14",
        "difficulty": "intermediate",
        "duration_minutes": 90,
        "player_count_min": 12,
        "player_count_max": 18,
        "description": "A 90-minute intermediate soccer session for U14 players focusing on maintaining possession under pressure and winning the ball back immediately after a turnover.",
        "overview": "The session progresses from Rondo possession work through a structured pressing game to a full scrimmage with pressing triggers coached in real time.",
        "phases": [
            {
                "name": "Warm-Up",
                "duration_minutes": 12,
                "color": "amber",
                "activities": [
                    "Dynamic warm-up: A-skips, lateral shuffles, leg swings, high knees",
                    "Rondo 4v1 (see Drills Library) — 3 rounds of 4 minutes",
                ],
            },
            {
                "name": "Possession Under Pressure",
                "duration_minutes": 20,
                "color": "blue",
                "activities": [
                    "6v3 possession in a 20x20 grid — 5 passes = 1 point",
                    "If defenders win the ball, they immediately become attackers and the team who lost it defends",
                    "Coaching focus: body shape, scanning, tempo of play",
                ],
            },
            {
                "name": "Pressing Shape",
                "duration_minutes": 20,
                "color": "orange",
                "activities": [
                    "Shadow pressing — coach walks ball through zones, team responds as a unit",
                    "Identify press triggers: back-pass, poor touch, goalkeeper with ball",
                    "4-4-2 compact shape walkthrough at 75%",
                ],
            },
            {
                "name": "Conditioned Game — Press or Possess",
                "duration_minutes": 25,
                "color": "purple",
                "activities": [
                    "8v8 on 60x40 field — team must win ball back within 6 seconds of losing it or concede a point",
                    "Freeze coaching: highlight good press triggers and poor press decisions",
                ],
            },
            {
                "name": "Cool-Down",
                "duration_minutes": 13,
                "color": "gray",
                "activities": [
                    "3-minute easy jog",
                    "Full-body stretch sequence (5 minutes)",
                    "Tactical debrief: name one moment we pressed well",
                ],
            },
        ],
        "equipment_list": ["cones", "pinnies (2 colours)", "soccer balls", "full-size goals"],
        "tags": ["intermediate", "possession", "pressing", "u14"],
        "is_featured": True,
    },

    # ── BASKETBALL ──────────────────────────────────────────────────────────
    {
        "title": "Basketball Beginner — Dribbling and Lay-Ups",
        "sport": "basketball",
        "age_bracket": "u10",
        "difficulty": "beginner",
        "duration_minutes": 60,
        "player_count_min": 6,
        "player_count_max": 14,
        "description": "A beginner U10 basketball session building dribbling confidence and teaching the lay-up as the foundational finishing skill.",
        "overview": "Players develop ball handling, transition into moving lay-ups, and finish with a fun competitive game that rewards dribbling.",
        "phases": [
            {
                "name": "Warm-Up",
                "duration_minutes": 10,
                "color": "amber",
                "activities": [
                    "2 laps jogging around the gym",
                    "Ball handling warmup: stationary dribbles — right hand, left hand, alternating",
                    "Ball Handling Figure 8 (see Drills Library) — 2 x 30 seconds",
                ],
            },
            {
                "name": "Technical — Dribbling",
                "duration_minutes": 15,
                "color": "blue",
                "activities": [
                    "Stationary low dribble: right hand 30 sec, left hand 30 sec, alternate 30 sec",
                    "Dribbling Slalom Course (see Drills Library) — 3 lanes, 4 trips each",
                    "Spider dribble: front-front, back-back alternating hands",
                ],
            },
            {
                "name": "Skill — Lay-Ups",
                "duration_minutes": 15,
                "color": "green",
                "activities": [
                    "Mikan Drill (see Drills Library) — 2 rounds of 60 seconds",
                    "Walking lay-up line: right side with right hand, left side with left hand",
                    "Dribble lay-up: full dribble approach from the three-point line",
                ],
            },
            {
                "name": "Game — Dribble Knockout",
                "duration_minutes": 15,
                "color": "purple",
                "activities": [
                    "Knockout: all players dribble in half-court, try to knock other balls out while protecting their own",
                    "Last player with a ball wins",
                    "Rule: must be dribbling at all times",
                ],
            },
            {
                "name": "Cool-Down",
                "duration_minutes": 5,
                "color": "gray",
                "activities": [
                    "Light jog half-court and back",
                    "Quad and hamstring stretches",
                    "High-five line",
                ],
            },
        ],
        "equipment_list": ["basketballs (1 per player)", "cones"],
        "tags": ["beginner", "dribbling", "lay-ups", "u10"],
        "is_featured": False,
    },
    {
        "title": "Basketball Intermediate — Team Offense",
        "sport": "basketball",
        "age_bracket": "u14",
        "difficulty": "intermediate",
        "duration_minutes": 90,
        "player_count_min": 10,
        "player_count_max": 15,
        "description": "A 90-minute intermediate basketball session for U14 players building on individual skills to install a basic motion offense and pick-and-roll action.",
        "overview": "Session moves from individual skill work to two-player concepts (pick and roll) and finishes with 5v5 emphasizing offensive movement and decision-making.",
        "phases": [
            {
                "name": "Warm-Up",
                "duration_minutes": 12,
                "color": "amber",
                "activities": [
                    "3-Man Weave (see Drills Library) — 4 minutes each group",
                    "Partner Passing (see Drills Library) — 20 chest, 20 bounce, 20 overhead",
                    "Defensive Slides — 3 trips side to side",
                ],
            },
            {
                "name": "Individual Skill Work",
                "duration_minutes": 18,
                "color": "blue",
                "activities": [
                    "Mikan Drill — 3 rounds of 60 seconds, track best score",
                    "Mid-range pull-up jumper off the dribble — 5 spots, 10 makes each",
                    "Defensive stance and closeout footwork",
                ],
            },
            {
                "name": "Two-Player Concepts — Pick and Roll",
                "duration_minutes": 20,
                "color": "green",
                "activities": [
                    "Pick and Roll Fundamentals (see Drills Library) — groups of 2, 5 reps each side",
                    "Add passive defender — ball handler reads switch or drop coverage",
                    "Discuss: when do we roll vs. pop?",
                ],
            },
            {
                "name": "5v5 Team Offense",
                "duration_minutes": 28,
                "color": "purple",
                "activities": [
                    "5v5 half-court — offense runs 3 possessions then rotates",
                    "Coaching focus: spacing (stay out of each other's areas), ball movement, use of the pick and roll",
                    "Award 2 points for a basket off the pick and roll",
                ],
            },
            {
                "name": "Cool-Down",
                "duration_minutes": 12,
                "color": "gray",
                "activities": [
                    "Free-throw shooting — each player shoots 10 free throws",
                    "Stretching circle",
                    "Team debrief: best pick-and-roll execution of the day",
                ],
            },
        ],
        "equipment_list": ["basketballs", "cones", "pinnies"],
        "tags": ["intermediate", "offense", "pick and roll", "u14"],
        "is_featured": True,
    },

    # ── BASEBALL ────────────────────────────────────────────────────────────
    {
        "title": "Baseball Beginner — Throwing and Fielding",
        "sport": "baseball",
        "age_bracket": "u10",
        "difficulty": "beginner",
        "duration_minutes": 60,
        "player_count_min": 8,
        "player_count_max": 16,
        "description": "A beginner U10 baseball session focused on safe throwing mechanics, catching, and basic ground ball fielding.",
        "overview": "Session builds arm care habits from day one — proper grip, throwing motion, and follow-through — before players attempt to field live ground balls.",
        "phases": [
            {
                "name": "Warm-Up",
                "duration_minutes": 10,
                "color": "amber",
                "activities": [
                    "Jog to the outfield and back",
                    "Arm circles: forward and backward, 15 each",
                    "Light long toss: pairs at 20 feet, work to 40 feet over 5 minutes",
                ],
            },
            {
                "name": "Throwing Mechanics",
                "duration_minutes": 15,
                "color": "blue",
                "activities": [
                    "Teach four-seam grip: fingers across the seams",
                    "Statue drill: front shoulder to target, step, throw — no windup",
                    "Four Corners Throwing (see Drills Library) — 5 rounds",
                ],
            },
            {
                "name": "Fielding — Ground Balls",
                "duration_minutes": 20,
                "color": "green",
                "activities": [
                    "Short hop practice: partner bounces ball from 5 feet, fielder scoops",
                    "Ground Ball Fielding drill (see Drills Library) — soft rollers first",
                    "Progress to rolled choppers down the line",
                ],
            },
            {
                "name": "Game — Running the Bases",
                "duration_minutes": 10,
                "color": "purple",
                "activities": [
                    "Base-running relay: teams race around the bases, fielders practice force outs",
                    "Coach hits fungos, players field and throw to first",
                ],
            },
            {
                "name": "Cool-Down",
                "duration_minutes": 5,
                "color": "gray",
                "activities": [
                    "Easy toss across the infield",
                    "Arm stretches: cross-body, overhead tricep",
                    "Team huddle",
                ],
            },
        ],
        "equipment_list": ["baseballs", "gloves", "bases", "bat", "helmets", "bucket"],
        "tags": ["beginner", "throwing", "fielding", "u10"],
        "is_featured": False,
    },
    {
        "title": "Baseball Intermediate — Hitting Focus",
        "sport": "baseball",
        "age_bracket": "u14",
        "difficulty": "intermediate",
        "duration_minutes": 90,
        "player_count_min": 10,
        "player_count_max": 16,
        "description": "A 90-minute hitting-focused intermediate session for U14 players progressing from tee work to live batting practice with situational hitting challenges.",
        "overview": "Players rotate through hitting stations while the rest of the squad works on pitching mechanics and fielding. Session ends with situational live BP.",
        "phases": [
            {
                "name": "Warm-Up and Arm Care",
                "duration_minutes": 15,
                "color": "amber",
                "activities": [
                    "Dynamic warm-up: leg swings, lunges, lateral shuffles",
                    "Arm care circuit: band pull-aparts, W's, external rotation — 2x15",
                    "Light long toss progression (20 to 80 feet)",
                ],
            },
            {
                "name": "Station 1 — Tee Work",
                "duration_minutes": 15,
                "color": "blue",
                "activities": [
                    "Tee Work Fundamentals (see Drills Library)",
                    "10 swings per position: high, middle, low, inside, outside",
                    "Partner gives feedback: 'did the barrel stay above the hands?'",
                ],
            },
            {
                "name": "Station 2 — Soft Toss and Front Toss",
                "duration_minutes": 15,
                "color": "green",
                "activities": [
                    "Soft Toss drill (see Drills Library) — 20 reps to each field zone",
                    "Front toss at 20 feet — emphasise opposite-field hitting on outside pitches",
                ],
            },
            {
                "name": "Pitching Group (parallel)",
                "duration_minutes": 20,
                "color": "orange",
                "activities": [
                    "Pitching Mechanics drill (see Drills Library) for pitchers",
                    "Non-pitchers: Ground Ball Fielding, Four Corners Throwing",
                ],
            },
            {
                "name": "Situational Live BP",
                "duration_minutes": 20,
                "color": "purple",
                "activities": [
                    "Coach pitches from 40 feet at controlled speed",
                    "Call a situation before each AB: 'Runner on 2nd, no outs — get the runner over'",
                    "Score execution, not just hits",
                ],
            },
            {
                "name": "Cool-Down",
                "duration_minutes": 5,
                "color": "gray",
                "activities": [
                    "Arm stretches and cool-down band work",
                    "Brief debrief: what pitch location did we hit best today?",
                ],
            },
        ],
        "equipment_list": ["batting tees", "baseballs", "bats", "helmets", "L-screen", "bucket", "resistance bands"],
        "tags": ["intermediate", "hitting", "BP", "u14"],
        "is_featured": False,
    },

    # ── FOOTBALL ────────────────────────────────────────────────────────────
    {
        "title": "Football Beginner — Fundamentals Day",
        "sport": "football",
        "age_bracket": "u10",
        "difficulty": "beginner",
        "duration_minutes": 60,
        "player_count_min": 10,
        "player_count_max": 20,
        "description": "A 60-minute introductory football session teaching snapping, hand-offs, route running basics, and safe tackling form — all without live contact.",
        "overview": "Players cycle through three skill stations before a flag-football scrimmage to apply the day's lessons in a game context.",
        "phases": [
            {
                "name": "Warm-Up",
                "duration_minutes": 10,
                "color": "amber",
                "activities": [
                    "High-knees, butt kicks, lateral shuffles across 10 yards",
                    "Backpedal and turn drill: 5 yards backpedal, plant, sprint 10 yards",
                    "Catch warm-up: easy tosses at 8 yards, work out to 15",
                ],
            },
            {
                "name": "Station A — Snap and Hand-Off",
                "duration_minutes": 12,
                "color": "blue",
                "activities": [
                    "Snap and Hand-Off Exchange drill (see Drills Library)",
                    "5 reps each way for every player at each position",
                ],
            },
            {
                "name": "Station B — Route Running",
                "duration_minutes": 12,
                "color": "green",
                "activities": [
                    "Route Running Basics (see Drills Library): slant, curl, out",
                    "3 reps of each route per player with a coach throw",
                ],
            },
            {
                "name": "Station C — Tackling Form",
                "duration_minutes": 12,
                "color": "orange",
                "activities": [
                    "Tackling Form drill (see Drills Library) — bags only, no live contact",
                    "Emphasis on eyes-up, wrap, and drive",
                ],
            },
            {
                "name": "Flag Football Scrimmage",
                "duration_minutes": 9,
                "color": "purple",
                "activities": [
                    "5v5 flag football — full field, coach-officiated",
                    "Award bonus points for completed hand-offs and sharp route breaks",
                ],
            },
            {
                "name": "Cool-Down",
                "duration_minutes": 5,
                "color": "gray",
                "activities": [
                    "Static stretches: quad, hamstring, hip flexor",
                    "Team talk: what is the most important safety rule in tackling?",
                ],
            },
        ],
        "equipment_list": ["footballs", "cones", "tackle bags", "flag belts", "helmets (if live tackle)", "pads"],
        "tags": ["beginner", "fundamentals", "flag football", "u10"],
        "is_featured": False,
    },
    {
        "title": "Football Intermediate — Passing Game",
        "sport": "football",
        "age_bracket": "u14",
        "difficulty": "intermediate",
        "duration_minutes": 90,
        "player_count_min": 14,
        "player_count_max": 22,
        "description": "A 90-minute intermediate football session for U14 focusing on the passing game: QB mechanics, route combinations, and 7-on-7 scrimmage.",
        "overview": "Offensive skill players develop timing and route concepts while defensive backs work coverage. The session culminates in a competitive 7-on-7 series.",
        "phases": [
            {
                "name": "Warm-Up",
                "duration_minutes": 12,
                "color": "amber",
                "activities": [
                    "Dynamic warm-up: high knees, skips, backpedals",
                    "Catch warm-up pairs: 10 yards, 15 yards, 20 yards",
                    "Route Running Basics (see Drills Library) — slant and out at half speed",
                ],
            },
            {
                "name": "QB — Drop Back Mechanics",
                "duration_minutes": 15,
                "color": "blue",
                "activities": [
                    "QB Footwork and Drop Backs drill (see Drills Library)",
                    "3-step, 5-step drops with a throw to a stationary receiver",
                    "Emphasis on eyes downfield during the drop",
                ],
            },
            {
                "name": "Route Combinations",
                "duration_minutes": 20,
                "color": "green",
                "activities": [
                    "Two-receiver combinations: slant-flat, curl-flat, out-post",
                    "QB reads primary then secondary in each combination",
                    "DBs run live coverage on each rep",
                ],
            },
            {
                "name": "7-on-7 Skeleton",
                "duration_minutes": 30,
                "color": "purple",
                "activities": [
                    "7-on-7 Skeleton drill (see Drills Library) — scripted first 10 plays, live last 10",
                    "Track: completions, incompletions, INTs, PBUs",
                    "Award defensive score for turnovers",
                ],
            },
            {
                "name": "Cool-Down",
                "duration_minutes": 13,
                "color": "gray",
                "activities": [
                    "Light jog end zone to end zone",
                    "Full-body stretch circuit",
                    "Film review preview: coach highlights one strong offensive series and one defensive series to discuss next session",
                ],
            },
        ],
        "equipment_list": ["footballs", "cones", "pinnies (2 colours)", "down markers"],
        "tags": ["intermediate", "passing game", "7-on-7", "u14"],
        "is_featured": False,
    },

    # ── VOLLEYBALL ──────────────────────────────────────────────────────────
    {
        "title": "Volleyball Beginner — Passing and Serving",
        "sport": "volleyball",
        "age_bracket": "u12",
        "difficulty": "beginner",
        "duration_minutes": 60,
        "player_count_min": 8,
        "player_count_max": 16,
        "description": "A 60-minute beginner volleyball session for U12 players introducing the forearm pass (bump), overhead set, and underhand serve.",
        "overview": "Players build the three fundamental contacts through progressive partner drills before combining them in a modified game.",
        "phases": [
            {
                "name": "Warm-Up",
                "duration_minutes": 8,
                "color": "amber",
                "activities": [
                    "2 laps of the gym jogging",
                    "Shoulder circles, arm swings, wrist rotations",
                    "Toss and catch with a partner to tune hand-eye coordination",
                ],
            },
            {
                "name": "Forearm Pass (Bump)",
                "duration_minutes": 15,
                "color": "blue",
                "activities": [
                    "Self-pass: toss ball to self and bump straight up 10x",
                    "Partner toss-and-bump: partner tosses, player bumps back to their hands",
                    "Pepper Drill (see Drills Library) — pass and set only, remove attack",
                ],
            },
            {
                "name": "Overhead Set",
                "duration_minutes": 12,
                "color": "green",
                "activities": [
                    "Setting Accuracy Targets (see Drills Library) — toss to self, set to target zone",
                    "Partner set: continuous back-and-forth setting rally",
                    "Introduce: set to position 4 from position 3",
                ],
            },
            {
                "name": "Underhand Serve",
                "duration_minutes": 15,
                "color": "orange",
                "activities": [
                    "Serve Receive Lines (see Drills Library) — underhand serves only",
                    "Step 1: serve from the attack line; step 2: serve from mid-court; step 3: from the service line",
                    "Receivers pass every serve to the setter target",
                ],
            },
            {
                "name": "Game — Modified 3v3",
                "duration_minutes": 7,
                "color": "purple",
                "activities": [
                    "3v3 on a lowered net or across the attack line",
                    "Ball must be bumped first — no catching allowed",
                    "First team to 10 points wins; rotate teams",
                ],
            },
            {
                "name": "Cool-Down",
                "duration_minutes": 3,
                "color": "gray",
                "activities": [
                    "Shoulder and forearm stretches",
                    "Share one thing you want to improve next practice",
                ],
            },
        ],
        "equipment_list": ["volleyballs", "net (adjustable height)", "cones or hoops for targets"],
        "tags": ["beginner", "passing", "serving", "u12"],
        "is_featured": False,
    },
    {
        "title": "Volleyball Intermediate — Full System Scrimmage",
        "sport": "volleyball",
        "age_bracket": "u16",
        "difficulty": "intermediate",
        "duration_minutes": 90,
        "player_count_min": 12,
        "player_count_max": 18,
        "description": "A 90-minute intermediate volleyball session for U16 integrating serve receive, offensive system, and blocking fundamentals into competitive scrimmage.",
        "overview": "Teams run a full pass-set-attack system with competitive serve receive. Defensive blocking footwork is reinforced before full-team scrimmage.",
        "phases": [
            {
                "name": "Warm-Up",
                "duration_minutes": 10,
                "color": "amber",
                "activities": [
                    "Pepper Drill (see Drills Library) — full sequence (pass, set, attack) 5 minutes",
                    "Dynamic gym warm-up: shuffles, backpedal, approach jumps",
                ],
            },
            {
                "name": "Serve Receive System",
                "duration_minutes": 20,
                "color": "blue",
                "activities": [
                    "Serve Receive Lines (see Drills Library) — float serves from the line",
                    "Full W-serve-receive formation — 5 receivers, setter at 3",
                    "Goal: 80% of passes land in the setter zone",
                ],
            },
            {
                "name": "Blocking Footwork",
                "duration_minutes": 15,
                "color": "orange",
                "activities": [
                    "Block Footwork drill (see Drills Library) — slide step and crossover",
                    "Middle blocker: reaction drill — coach points left/right, MB moves and jumps",
                    "Outside/right-side: approach angle from the pin position",
                ],
            },
            {
                "name": "3-Hit Combination System",
                "duration_minutes": 15,
                "color": "green",
                "activities": [
                    "3-Hit Combination drill (see Drills Library)",
                    "Coach feeds free balls; team runs 3 reps per rotation",
                    "Track: kills vs errors across all rotations",
                ],
            },
            {
                "name": "Full Scrimmage",
                "duration_minutes": 25,
                "color": "purple",
                "activities": [
                    "6v6 rally-score scrimmage — race to 25 (cap at 27)",
                    "Sub every 5 points to keep all players active",
                    "Coaching stops only for systematic errors (not individual mistakes)",
                ],
            },
            {
                "name": "Cool-Down",
                "duration_minutes": 5,
                "color": "gray",
                "activities": [
                    "Jump serve development (see Drills Library) — 5 serves per player",
                    "Team stretch circle",
                    "Statistical review: who led the team in kills? In aces?",
                ],
            },
        ],
        "equipment_list": ["volleyballs", "net", "cones", "scorekeeper whiteboard"],
        "tags": ["intermediate", "full system", "scrimmage", "u16"],
        "is_featured": True,
    },
]


# ---------------------------------------------------------------------------
# Seed functions
# ---------------------------------------------------------------------------


async def seed_drills(db: AsyncSession) -> int:
    """Insert drill seed data if the drills table is empty.

    Returns the number of drills inserted (0 if table was already populated).
    """
    count_result = await db.execute(select(func.count()).select_from(Drill))
    existing = count_result.scalar_one()
    if existing > 0:
        return 0

    drills = [Drill(**data) for data in DRILL_DATA]
    db.add_all(drills)
    await db.commit()
    return len(drills)


async def seed_templates(db: AsyncSession) -> int:
    """Insert practice template seed data if the practice_templates table is empty.

    Returns the number of templates inserted (0 if table was already populated).
    """
    count_result = await db.execute(
        select(func.count()).select_from(PracticeTemplate)
    )
    existing = count_result.scalar_one()
    if existing > 0:
        return 0

    templates = [PracticeTemplate(**data) for data in TEMPLATE_DATA]
    db.add_all(templates)
    await db.commit()
    return len(templates)
