"""Baseline soccer rules seeded from AYSO / US Youth Soccer / FIFA Youth modifications."""

SOCCER_RULES = [
    # ── GAME DURATION ────────────────────────────────────────────────────────
    {
        "sport": "soccer", "category": "game_duration", "subcategory": "period_length",
        "rule_tier": "baseline", "rule_type": "numeric",
        "canonical_text": "U6 games consist of four 6-minute quarters.",
        "plain_language_text": "Each U6 game has 4 quarters, 6 minutes each.",
        "scope": {"age_brackets": ["U6"], "division_types": ["all"], "league_levels": ["all"]},
        "numeric_value": 6, "numeric_unit": "minutes_per_quarter",
        "safety_critical": False, "game_day_critical": True, "display_priority": 1,
        "governing_body_source": "AYSO", "tags": ["game_duration", "U6"],
    },
    {
        "sport": "soccer", "category": "game_duration", "subcategory": "period_length",
        "rule_tier": "baseline", "rule_type": "numeric",
        "canonical_text": "U8 games consist of four 10-minute quarters.",
        "plain_language_text": "Each U8 game has 4 quarters, 10 minutes each (40 min total).",
        "scope": {"age_brackets": ["U8"], "division_types": ["all"], "league_levels": ["all"]},
        "numeric_value": 10, "numeric_unit": "minutes_per_quarter",
        "safety_critical": False, "game_day_critical": True, "display_priority": 1,
        "governing_body_source": "AYSO", "tags": ["game_duration", "U8"],
    },
    {
        "sport": "soccer", "category": "game_duration", "subcategory": "period_length",
        "rule_tier": "baseline", "rule_type": "numeric",
        "canonical_text": "U10 games consist of two 25-minute halves.",
        "plain_language_text": "Each U10 game has 2 halves of 25 minutes each (50 min total).",
        "scope": {"age_brackets": ["U10"], "division_types": ["all"], "league_levels": ["all"]},
        "numeric_value": 25, "numeric_unit": "minutes_per_half",
        "safety_critical": False, "game_day_critical": True, "display_priority": 1,
        "governing_body_source": "AYSO", "tags": ["game_duration", "U10"],
    },
    {
        "sport": "soccer", "category": "game_duration", "subcategory": "period_length",
        "rule_tier": "baseline", "rule_type": "numeric",
        "canonical_text": "U11 and U12 games consist of two 30-minute halves.",
        "plain_language_text": "U11/U12 games are 2 halves of 30 minutes each (60 min total).",
        "scope": {"age_brackets": ["U11", "U12"], "division_types": ["all"], "league_levels": ["all"]},
        "numeric_value": 30, "numeric_unit": "minutes_per_half",
        "safety_critical": False, "game_day_critical": True, "display_priority": 1,
        "governing_body_source": "AYSO", "tags": ["game_duration", "U11", "U12"],
    },
    {
        "sport": "soccer", "category": "game_duration", "subcategory": "period_length",
        "rule_tier": "baseline", "rule_type": "numeric",
        "canonical_text": "U14 games consist of two 35-minute halves.",
        "plain_language_text": "U14 games are 2 halves of 35 minutes each (70 min total).",
        "scope": {"age_brackets": ["U14"], "division_types": ["all"], "league_levels": ["all"]},
        "numeric_value": 35, "numeric_unit": "minutes_per_half",
        "safety_critical": False, "game_day_critical": True, "display_priority": 1,
        "governing_body_source": "AYSO", "tags": ["game_duration", "U14"],
    },
    {
        "sport": "soccer", "category": "game_duration", "subcategory": "period_length",
        "rule_tier": "baseline", "rule_type": "numeric",
        "canonical_text": "U16, U18, and high school games consist of two 40-minute halves.",
        "plain_language_text": "U16+ games are 2 halves of 40 minutes each (80 min total).",
        "scope": {"age_brackets": ["U16", "U18", "high_school"], "division_types": ["all"], "league_levels": ["all"]},
        "numeric_value": 40, "numeric_unit": "minutes_per_half",
        "safety_critical": False, "game_day_critical": True, "display_priority": 1,
        "governing_body_source": "NFHS", "tags": ["game_duration", "U16", "U18", "high_school"],
    },

    # ── BALL SIZE ────────────────────────────────────────────────────────────
    {
        "sport": "soccer", "category": "ball_size", "subcategory": "official_ball",
        "rule_tier": "baseline", "rule_type": "numeric",
        "canonical_text": "Size 3 ball is used for all players U8 and under.",
        "plain_language_text": "U6 and U8 players use a Size 3 ball.",
        "scope": {"age_brackets": ["U6", "U8"], "division_types": ["all"], "league_levels": ["all"]},
        "numeric_value": 3, "numeric_unit": "ball_size",
        "safety_critical": False, "game_day_critical": True, "display_priority": 2,
        "governing_body_source": "AYSO", "tags": ["equipment", "ball_size"],
    },
    {
        "sport": "soccer", "category": "ball_size", "subcategory": "official_ball",
        "rule_tier": "baseline", "rule_type": "numeric",
        "canonical_text": "Size 4 ball is used for all players ages U10 through U12.",
        "plain_language_text": "U10, U11, and U12 players use a Size 4 ball.",
        "scope": {"age_brackets": ["U10", "U11", "U12"], "division_types": ["all"], "league_levels": ["all"]},
        "numeric_value": 4, "numeric_unit": "ball_size",
        "safety_critical": False, "game_day_critical": True, "display_priority": 2,
        "governing_body_source": "AYSO", "tags": ["equipment", "ball_size"],
    },
    {
        "sport": "soccer", "category": "ball_size", "subcategory": "official_ball",
        "rule_tier": "baseline", "rule_type": "numeric",
        "canonical_text": "Size 5 ball is used for all players U14 and older.",
        "plain_language_text": "U14 and above use the standard Size 5 ball.",
        "scope": {"age_brackets": ["U14", "U16", "U18", "high_school"], "division_types": ["all"], "league_levels": ["all"]},
        "numeric_value": 5, "numeric_unit": "ball_size",
        "safety_critical": False, "game_day_critical": True, "display_priority": 2,
        "governing_body_source": "FIFA", "tags": ["equipment", "ball_size"],
    },

    # ── HEADING RESTRICTIONS ─────────────────────────────────────────────────
    {
        "sport": "soccer", "category": "heading_restrictions", "subcategory": "heading_ban",
        "rule_tier": "baseline", "rule_type": "boolean",
        "canonical_text": "Heading is strictly prohibited for all players U11 and under. A referee must award an indirect free kick to the opposing team at the spot of the infraction if a player deliberately heads the ball.",
        "plain_language_text": "Players U11 and younger are BANNED from heading the ball. If it happens, the other team gets a free kick.",
        "scope": {"age_brackets": ["U6", "U8", "U10", "U11"], "division_types": ["all"], "league_levels": ["all"]},
        "safety_critical": True, "game_day_critical": True, "display_priority": 3,
        "governing_body_source": "US_Youth_Soccer", "tags": ["heading", "safety", "U11_and_under"],
        "normative_certainty": 0.99,
    },
    {
        "sport": "soccer", "category": "heading_restrictions", "subcategory": "heading_allowed",
        "rule_tier": "baseline", "rule_type": "boolean",
        "canonical_text": "Heading is permitted for all players U12 and older per standard FIFA rules.",
        "plain_language_text": "Players U12 and older are allowed to head the ball.",
        "scope": {"age_brackets": ["U12", "U14", "U16", "U18", "high_school"], "division_types": ["all"], "league_levels": ["all"]},
        "safety_critical": False, "game_day_critical": False, "display_priority": 50,
        "governing_body_source": "FIFA", "tags": ["heading"],
        "normative_certainty": 0.99,
    },

    # ── SLIDE TACKLING ───────────────────────────────────────────────────────
    {
        "sport": "soccer", "category": "slide_tackle_rules", "subcategory": "slide_tackle_ban",
        "rule_tier": "baseline", "rule_type": "boolean",
        "canonical_text": "Slide tackling is prohibited for all players U10 and under.",
        "plain_language_text": "No slide tackles allowed for U10 and younger.",
        "scope": {"age_brackets": ["U6", "U8", "U10"], "division_types": ["all"], "league_levels": ["all"]},
        "safety_critical": True, "game_day_critical": False, "display_priority": 20,
        "governing_body_source": "AYSO", "tags": ["tackling", "safety"],
        "normative_certainty": 0.95,
    },
    {
        "sport": "soccer", "category": "slide_tackle_rules", "subcategory": "slide_tackle_allowed",
        "rule_tier": "baseline", "rule_type": "boolean",
        "canonical_text": "Slide tackling is permitted for players U12 and older when performed safely and without dangerous play. U11 leagues may restrict slide tackling at local discretion.",
        "plain_language_text": "U12+ players can slide tackle. U11 depends on the league.",
        "scope": {"age_brackets": ["U11", "U12", "U14", "U16", "U18", "high_school"], "division_types": ["all"], "league_levels": ["all"]},
        "safety_critical": False, "game_day_critical": False, "display_priority": 30,
        "governing_body_source": "FIFA", "tags": ["tackling"],
        "normative_certainty": 0.85,
    },

    # ── BUILD-OUT LINE ───────────────────────────────────────────────────────
    {
        "sport": "soccer", "category": "build_out_line", "subcategory": "build_out_active",
        "rule_tier": "baseline", "rule_type": "boolean",
        "canonical_text": "A build-out line is in effect for U8 and U10 divisions. When the goalkeeper has the ball (goal kick or in hands), all opposing players must retreat behind the build-out line until the ball is played.",
        "plain_language_text": "U8 and U10: When the keeper has the ball, the other team must back up to the build-out line before play continues.",
        "scope": {"age_brackets": ["U8", "U10"], "division_types": ["all"], "league_levels": ["all"]},
        "safety_critical": False, "game_day_critical": False, "display_priority": 25,
        "governing_body_source": "US_Youth_Soccer", "tags": ["build_out_line", "goalkeeper"],
        "normative_certainty": 0.97,
    },

    # ── SUBSTITUTIONS ────────────────────────────────────────────────────────
    {
        "sport": "soccer", "category": "substitution_policy", "subcategory": "sub_windows",
        "rule_tier": "baseline", "rule_type": "prose",
        "canonical_text": "For recreational divisions U12 and under, unlimited substitutions are permitted at any stoppage of play with referee permission. In competitive and travel divisions U14 and under, substitutions are permitted at goal kicks, throw-ins, after a goal, at halftime, and after an injury. High school follows NFHS rules: substitutions only at stoppages with referee acknowledgment.",
        "plain_language_text": "Rec U12-: sub any time play stops. Competitive U14-: sub at goal kicks, throw-ins, goals, halftime, injuries. HS: sub at any stoppage with referee OK.",
        "scope": {"age_brackets": ["all"], "division_types": ["all"], "league_levels": ["all"]},
        "safety_critical": False, "game_day_critical": True, "display_priority": 4,
        "governing_body_source": "AYSO", "tags": ["substitutions"],
        "normative_certainty": 0.88,
    },

    # ── GOALKEEPER RULES ─────────────────────────────────────────────────────
    {
        "sport": "soccer", "category": "goalkeeper_rules", "subcategory": "backpass_rule",
        "rule_tier": "baseline", "rule_type": "boolean",
        "canonical_text": "A goalkeeper may not handle (pick up) a ball that has been deliberately kicked to them by a teammate using their feet. An indirect free kick is awarded to the opposing team. This rule applies at all age levels U10 and above.",
        "plain_language_text": "If a teammate kicks the ball back to the keeper with their foot on purpose, the keeper CANNOT pick it up — that is an indirect free kick for the other team. This applies U10 and up.",
        "scope": {"age_brackets": ["U10", "U11", "U12", "U14", "U16", "U18", "high_school"], "division_types": ["all"], "league_levels": ["all"]},
        "safety_critical": False, "game_day_critical": False, "display_priority": 40,
        "governing_body_source": "FIFA", "tags": ["goalkeeper", "backpass_rule"],
        "normative_certainty": 0.99,
    },
    {
        "sport": "soccer", "category": "goalkeeper_rules", "subcategory": "backpass_rule_u8",
        "rule_tier": "baseline", "rule_type": "boolean",
        "canonical_text": "The backpass rule is waived for U8 and below. Goalkeepers may freely handle the ball regardless of how it was passed to them.",
        "plain_language_text": "U6 and U8: the keeper can pick up the ball even if a teammate kicked it to them.",
        "scope": {"age_brackets": ["U6", "U8"], "division_types": ["all"], "league_levels": ["all"]},
        "safety_critical": False, "game_day_critical": False, "display_priority": 40,
        "governing_body_source": "AYSO", "tags": ["goalkeeper", "backpass_rule"],
        "normative_certainty": 0.95,
    },

    # ── PLAYER MINIMUMS ──────────────────────────────────────────────────────
    {
        "sport": "soccer", "category": "player_minimum", "subcategory": "field_players",
        "rule_tier": "baseline", "rule_type": "numeric",
        "canonical_text": "U6 plays 3v3 or 4v4 (no goalkeeper). U8 plays 4v4 (no goalkeeper). U10 plays 7v7. U11 and U12 play 9v9. U14 and above play 11v11. A team may not start or continue a game with fewer than the stated minimum minus 2 players.",
        "plain_language_text": "Player counts: U6=3-4 per side (no keeper), U8=4 per side (no keeper), U10=7v7, U11/U12=9v9, U14+=11v11.",
        "scope": {"age_brackets": ["all"], "division_types": ["all"], "league_levels": ["all"]},
        "safety_critical": False, "game_day_critical": True, "display_priority": 5,
        "governing_body_source": "AYSO", "tags": ["roster", "player_count"],
        "normative_certainty": 0.96,
    },

    # ── OFFSIDE ──────────────────────────────────────────────────────────────
    {
        "sport": "soccer", "category": "offside_modifications", "subcategory": "offside_u8",
        "rule_tier": "baseline", "rule_type": "boolean",
        "canonical_text": "Offside is not enforced for U8 and below.",
        "plain_language_text": "No offside rule for U6 and U8 games.",
        "scope": {"age_brackets": ["U6", "U8"], "division_types": ["all"], "league_levels": ["all"]},
        "safety_critical": False, "game_day_critical": False, "display_priority": 35,
        "governing_body_source": "AYSO", "tags": ["offside"],
        "normative_certainty": 0.97,
    },
    {
        "sport": "soccer", "category": "offside_modifications", "subcategory": "offside_standard",
        "rule_tier": "baseline", "rule_type": "boolean",
        "canonical_text": "Standard FIFA offside rules apply for all players U10 and older.",
        "plain_language_text": "Normal offside rules apply from U10 upward.",
        "scope": {"age_brackets": ["U10", "U11", "U12", "U14", "U16", "U18", "high_school"], "division_types": ["all"], "league_levels": ["all"]},
        "safety_critical": False, "game_day_critical": False, "display_priority": 35,
        "governing_body_source": "FIFA", "tags": ["offside"],
        "normative_certainty": 0.99,
    },

    # ── CONCUSSION PROTOCOL ──────────────────────────────────────────────────
    {
        "sport": "soccer", "category": "concussion_protocol", "subcategory": "return_to_play",
        "rule_tier": "baseline", "rule_type": "prose",
        "canonical_text": "Any player suspected of sustaining a concussion must be immediately removed from play and may not return to play the same day. Return to play requires written medical clearance from a licensed healthcare professional. No player may return to play without following a graduated return-to-play protocol.",
        "plain_language_text": "If a player might have a concussion, pull them out immediately. They CANNOT return the same day. A doctor must clear them in writing before they play again.",
        "scope": {"age_brackets": ["all"], "division_types": ["all"], "league_levels": ["all"]},
        "safety_critical": True, "game_day_critical": False, "display_priority": 5,
        "governing_body_source": "CDC_HeadsUp", "tags": ["concussion", "safety", "return_to_play"],
        "normative_certainty": 0.99,
    },
]
